name: Build, Bump Version, Release, and Publish to PyPI

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write # Để push code, tạo tag, release
  id-token: write # Để publish lên PyPI (Trusted Publishing)

jobs:
  # 1. Build và kiểm tra xem có lỗi gì không trước khi làm các bước khác
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/
          
  # 2. Bump version, nếu build thành công
  bump-version:
    runs-on: ubuntu-latest
    needs: build # Chỉ chạy khi build thành công
    outputs:
      NEW_VERSION: ${{ steps.bump.outputs.new_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install bump2version
        run: pip install bump2version

      - name: Bump version (patch)
        id: bump
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          NEW_VERSION=$(bump2version patch --list | grep new_version | sed -r s,"^new_version=",,)
          echo "new_version=$NEW_VERSION" >> "$GITHUB_ENV"
          echo "new_version=$NEW_VERSION" >> "$GITHUB_OUTPUT"

      - name: Push changes with tag
        run: |
          git push --follow-tags

  # 3. Tạo Release trên GitHub
  create-release:
    runs-on: ubuntu-latest
    needs: bump-version
    steps:
      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ needs.bump-version.outputs.NEW_VERSION }}
          name: Release v${{ needs.bump-version.outputs.NEW_VERSION }}
          body: "Automated release for version v${{ needs.bump-version.outputs.NEW_VERSION }}."
          draft: false
          prerelease: false

  # 4. Publish lên PyPI
  publish-pypi:
    runs-on: ubuntu-latest
    needs: [bump-version, create-release]
    permissions:
      # Cấp quyền cho OIDC để thực hiện trusted publishing (nếu cần)
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/


