name: Upload Python Package to PyPI

# Trigger workflow khi có một release mới được publish
on:
  workflow_dispatch:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Upgrade pip and install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build release distributions
        run: |
          python -m build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-distributions
          path: dist/

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      # Cấp quyền cho OIDC để thực hiện trusted publishing (nếu cần)
      id-token: write
    environment:
      name: pypi
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: package-distributions
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
